# Generated by Django 5.1.2 on 2024-11-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_score', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='selected_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
